blank_issues_enabled: false
contact_links:
  - name: Valour Website
    url: https://valour.gg/
    about: The Valour Website
  - name: Valour Contact
    url: https://static.valour.gg/contact/
    about: Where you can find our contact information (WIP)
